// <auto-generated />
using System;
using Deskmate.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Deskmate.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DeskmateDbContext))]
    [Migration("20260925011057_AddReducedMotion")]
    partial class AddReducedMotion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Deskmate.Core.Models.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("AlertBefore")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AlertDayBefore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlertOnDay")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Recurrence")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly?>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("Deskmate.Core.Models.ReminderOccurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AdvanceShown")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DayBeforeShown")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OnDayShown")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OverdueShown")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReminderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("SnoozedUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReminderOccurrences");
                });

            modelBuilder.Entity("Deskmate.Core.Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarPack")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("AvatarScale")
                        .HasColumnType("REAL");

                    b.Property<TimeSpan>("BreakAfter")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentFocus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("FirstRunCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("LastGreetingDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("PositionX")
                        .HasColumnType("REAL");

                    b.Property<double?>("PositionY")
                        .HasColumnType("REAL");

                    b.Property<TimeOnly?>("QuietHoursEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("QuietHoursStart")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReducedMotion")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("SleepAfter")
                        .HasColumnType("TEXT");

                    b.Property<bool>("StartAtLogin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("WorkEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("WorkStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
