// <auto-generated />
using System;
using Deskmate.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Deskmate.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DeskmateDbContext))]
    partial class DeskmateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Deskmate.Core.Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarPack")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("AvatarScale")
                        .HasColumnType("REAL");

                    b.Property<TimeSpan>("BreakAfter")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentFocus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("FirstRunCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("LastGreetingDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("PositionX")
                        .HasColumnType("REAL");

                    b.Property<double?>("PositionY")
                        .HasColumnType("REAL");

                    b.Property<TimeSpan>("SleepAfter")
                        .HasColumnType("TEXT");

                    b.Property<bool>("StartAtLogin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("WorkEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("WorkStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
